# Generated by Django 5.0.14 on 2026-04-21 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('hoc', '0002_alter_hocuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('source_store_id', models.CharField(max_length=20)),
                ('destination_store_id', models.CharField(max_length=20)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('transporter', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('lr_number', models.CharField(blank=True, max_length=50)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('transfer_rate_type', models.CharField(choices=[('at_cost', 'At Cost'), ('at_landed_cost', 'At Landed Cost'), ('at_mrp', 'At MRP'), ('at_transfer_price', 'At Transfer Price')], default='at_cost', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ayy_inventory_transfer',
            },
        ),
        migrations.CreateModel(
            name='StockValuationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=20, unique=True)),
                ('method', models.CharField(choices=[('weighted_average_cost', 'Weighted Average Cost'), ('fifo', 'First-In-First-Out'), ('mrp_based', 'MRP-Based')], default='weighted_average_cost', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ayy_inventory_valuation_method',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('kit_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bundle_variant', models.ForeignKey(limit_choices_to={'style__sub_category__hsn_code': ''}, on_delete=django.db.models.deletion.PROTECT, related_name='kits', to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_kit',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('adjustment_type', models.CharField(choices=[('positive', '+'), ('negative', '-')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reason_code', models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft/Shrinkage'), ('sample', 'Sample Issue'), ('internal_consumption', 'Internal Consumption'), ('found', 'Found'), ('system_correction', 'System Correction'), ('pi_variance', 'PI Variance')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.CharField(max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('customer_reservation', 'Customer Reservation'), ('alteration', 'Alteration'), ('display_piece', 'Display Piece'), ('legal_hold', 'Legal Hold')], max_length=50)),
                ('held_by', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('auto_release_at', models.DateTimeField(blank=True, null=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_stock_hold',
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.kit')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_kit_component',
                'unique_together': {('kit', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='StockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('event_type', models.CharField(choices=[('inward', 'Inward (GRN)'), ('outward', 'Outward (Sale)'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('physical_count', 'Physical Count'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('kit_build', 'Kit Build'), ('kit_debuild', 'Kit Debuild'), ('qc_hold', 'QC Hold'), ('qc_release', 'QC Release')], max_length=30)),
                ('quantity', models.BigIntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('lamport_timestamp', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_events', to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_stock_event',
                'ordering': ['lamport_timestamp', 'id'],
                'indexes': [models.Index(fields=['store_id', 'variant', 'lamport_timestamp'], name='ayy_invento_store_i_3c0105_idx'), models.Index(fields=['store_id', 'event_type'], name='ayy_invento_store_i_ebc9a6_idx'), models.Index(fields=['reference_type', 'reference_id'], name='ayy_invento_referen_628bb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_store_id', models.CharField(default='store-0001', max_length=20)),
                ('on_hand', models.BigIntegerField(default=0)),
                ('reserved', models.BigIntegerField(default=0)),
                ('allocated', models.BigIntegerField(default=0)),
                ('in_transit', models.BigIntegerField(default=0)),
                ('pending_qc', models.BigIntegerField(default=0)),
                ('sellable', models.BigIntegerField(default=0)),
                ('valued_at_paise', models.PositiveIntegerField(default=0)),
                ('last_event_lamport', models.PositiveBigIntegerField(default=0)),
                ('last_recomputed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='hoc.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_inventory_stock_level',
                'indexes': [models.Index(fields=['org_store_id', 'sellable'], name='ayy_invento_org_sto_b12bc7_idx')],
                'unique_together': {('org_store_id', 'variant')},
            },
        ),
    ]
