# Generated by Django 5.0.14 on 2026-04-21 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVoucherLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('date', models.DateField()),
                ('xml_content', models.TextField()),
                ('tally_version', models.CharField(default='erp_9', max_length=20)),
                ('total_bills', models.PositiveIntegerField(default=0)),
                ('total_sales_paise', models.PositiveIntegerField(default=0)),
                ('total_tax_paise', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ayy_tally_voucher_log',
                'ordering': ['-date'],
                'unique_together': {('store_id', 'date')},
            },
        ),
    ]
