# Generated by Django 5.0.14 on 2026-04-21 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('anomaly_type', models.CharField(max_length=50)),
                ('outbox_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ayy_sync_reconciliation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('client_lamport_highwater', models.PositiveBigIntegerField(default=0)),
                ('server_lamport_highwater', models.PositiveBigIntegerField(default=0)),
                ('items_pushed', models.PositiveIntegerField(default=0)),
                ('items_pull', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
            ],
            options={
                'db_table': 'ayy_sync_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloud_event_id', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('source_store_id', models.CharField(max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ayy_sync_cloud_event',
                'unique_together': {('cloud_event_id', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('outbox_id', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acked', 'Acked')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ayy_sync_outbox',
                'ordering': ['outbox_id'],
                'indexes': [models.Index(fields=['store_id', 'status', 'outbox_id'], name='ayy_sync_ou_store_i_86fc22_idx'), models.Index(fields=['entity_type', 'entity_id'], name='ayy_sync_ou_entity__708eb0_idx')],
                'unique_together': {('store_id', 'outbox_id')},
            },
        ),
    ]
