# Generated by Django 5.0.14 on 2026-04-21 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ayy_catalogue_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'db_table': 'ayy_catalogue_colour',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('unit', models.CharField(default='piece', max_length=10)),
            ],
            options={
                'db_table': 'ayy_catalogue_size',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('hsn_code', models.CharField(choices=[('0906', 'Spices'), ('6109', 'T-shirts & singlets'), ('6110', 'Sweaters & pullovers'), ('6203', "Men's garments (woven)"), ('6204', "Women's garments (woven)"), ('6103', "Men's garments (knitted)"), ('6104', "Women's garments (knitted)"), ('6115', 'Pantyhose & tights'), ('6217', 'Made-up accessories'), ('5111', 'Sarees & dhotis (silk)'), ('6117', 'Fashion accessories'), ('6403', 'Footwear (sports)'), ('6404', 'Footwear (casual)')], default='6109', max_length=10)),
                ('gst_slab', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalogue.category')),
            ],
            options={
                'db_table': 'ayy_catalogue_subcategory',
                'ordering': ['code'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=200)),
                ('style_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('collection', models.CharField(blank=True, max_length=100)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('end_of_life_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='catalogue.subcategory')),
            ],
            options={
                'db_table': 'ayy_catalogue_style',
                'ordering': ['-created_at'],
                'unique_together': {('sub_category', 'style_code')},
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(editable=False, max_length=30, unique=True)),
                ('barcode', models.CharField(editable=False, max_length=13, unique=True)),
                ('mrp_paise', models.PositiveIntegerField(help_text='MRP in paise (Rs * 100)')),
                ('cost_price_paise', models.PositiveIntegerField(help_text='Cost price in paise')),
                ('selling_price_paise', models.PositiveIntegerField(help_text='Selling price in paise')),
                ('old_mrp_paise', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.colour')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.size')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalogue.style')),
            ],
            options={
                'db_table': 'ayy_catalogue_variant',
                'ordering': ['style', 'colour', 'size'],
            },
        ),
        migrations.CreateModel(
            name='StatePriceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gstin_state_code', models.CharField(help_text='2-digit GSTIN state code', max_length=2)),
                ('mrp_paise', models.PositiveIntegerField()),
                ('selling_price_paise', models.PositiveIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_prices', to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_catalogue_state_price',
            },
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['barcode'], name='ayy_catalog_barcode_eaca38_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['style', 'colour', 'size'], name='ayy_catalog_style_i_276340_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('style', 'colour', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='statepriceoverride',
            unique_together={('variant', 'gstin_state_code')},
        ),
    ]
