# Generated by Django 5.0.14 on 2026-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('catalogue_editor', 'Catalogue Editor'), ('reconciliation', 'Reconciliation'), ('store_manager', 'Store Manager')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingreconciliation',
            name='reason',
            field=models.CharField(choices=[('stock_mismatch', 'Stock Mismatch'), ('return_not_synced', 'Return Not Synced'), ('negative_stock', 'Negative Stock'), ('payload_divergence', 'Payload Divergence')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('received', 'Received'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
    ]
