# Generated by Django 5.0.14 on 2026-04-21 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(default='silver', max_length=20)),
                ('trailing_12m_spend_paise', models.PositiveIntegerField(default=0)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_channel', models.CharField(blank=True, max_length=50)),
                ('consent_withdrawn', models.BooleanField(default=False)),
                ('consent_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('data_erased', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ayy_customers_customer',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('coupon_type', models.CharField(choices=[('flat_pct', 'Flat % Discount'), ('flat_rs', 'Flat Rs Discount'), ('buy_x_get_y', 'Buy X Get Y'), ('bundle_price', 'Bundle Price')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_purchase_paise', models.PositiveIntegerField(default=0)),
                ('max_discount_paise', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('customer_specific', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'db_table': 'ayy_customers_coupon',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('expire', 'Expired'), ('bonus', 'Bonus')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customers.customer')),
            ],
            options={
                'db_table': 'ayy_customers_loyalty_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMerge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.CharField(blank=True, max_length=50)),
                ('merged_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_merged', to='customers.customer')),
                ('primary_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merges_as_primary', to='customers.customer')),
            ],
            options={
                'db_table': 'ayy_customers_merge',
                'unique_together': {('primary_customer', 'merged_customer')},
            },
        ),
    ]
