# Generated by Django 5.0.14 on 2026-04-21 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='store-0001', max_length=20)),
                ('bill_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('cashier_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_mobile', models.CharField(blank=True, max_length=10)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('held_by', models.CharField(blank=True, max_length=50)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_paise', models.PositiveIntegerField(default=0)),
                ('discount_paise', models.PositiveIntegerField(default=0)),
                ('taxable_value_paise', models.PositiveIntegerField(default=0)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('cgst_paise', models.PositiveIntegerField(default=0)),
                ('sgst_paise', models.PositiveIntegerField(default=0)),
                ('igst_paise', models.PositiveIntegerField(default=0)),
                ('cess_paise', models.PositiveIntegerField(default=0)),
                ('total_paise', models.PositiveIntegerField(default=0)),
                ('total_paid_paise', models.PositiveIntegerField(default=0)),
                ('balance_due_paise', models.PositiveIntegerField(default=0)),
                ('is_inter_state', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=120)),
                ('outbox_id', models.PositiveBigIntegerField(default=0, editable=False)),
                ('is_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='customers.customer')),
            ],
            options={
                'db_table': 'ayy_till_bill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('held_by', models.CharField(max_length=50)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_by', models.CharField(blank=True, max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='billing.bill')),
            ],
            options={
                'db_table': 'ayy_till_bill_hold',
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_paise', models.PositiveIntegerField()),
                ('mrp_paise', models.PositiveIntegerField()),
                ('line_discount_paise', models.PositiveIntegerField(default=0)),
                ('taxable_value_paise', models.PositiveIntegerField(default=0)),
                ('hsn_code', models.CharField(max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_paise', models.PositiveIntegerField(default=0)),
                ('sgst_paise', models.PositiveIntegerField(default=0)),
                ('igst_paise', models.PositiveIntegerField(default=0)),
                ('discount_override', models.BooleanField(default=False)),
                ('overridden_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.bill')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='catalogue.variant')),
            ],
            options={
                'db_table': 'ayy_till_bill_line',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tender_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('gift_voucher', 'Gift Voucher'), ('store_credit', 'Store Credit'), ('loyalty_points', 'Loyalty Points')], max_length=30)),
                ('amount_paise', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill')),
            ],
            options={
                'db_table': 'ayy_till_bill_payment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('reason', models.CharField(max_length=100)),
                ('refund_mode', models.CharField(choices=[('original_tender', 'Original Tender'), ('store_credit', 'Store Credit'), ('either', 'Either')], default='original_tender', max_length=20)),
                ('is_exchange', models.BooleanField(default=False)),
                ('credit_paise', models.PositiveIntegerField(default=0)),
                ('credit_validity_days', models.PositiveIntegerField(default=90)),
                ('credit_expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending_qc', max_length=20)),
                ('qc_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('credit_note_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('credit_note_cgst_paise', models.PositiveIntegerField(default=0)),
                ('credit_note_sgst_paise', models.PositiveIntegerField(default=0)),
                ('credit_note_igst_paise', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='catalogue.variant')),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.bill')),
            ],
            options={
                'db_table': 'ayt_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['store_id', '-created_at'], name='ayy_till_bi_store_i_547719_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['bill_number'], name='ayy_till_bi_bill_nu_f36e57_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['status'], name='ayy_till_bi_status_df0448_idx'),
        ),
    ]
