# Generated by Django 5.0.14 on 2026-04-21 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRPError',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('requires_action', models.BooleanField(default=True)),
                ('action_description', models.TextField(blank=True)),
                ('retryable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ayy_irp_error_taxonomy',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gstrn', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=30)),
                ('irn', models.CharField(blank=True, max_length=40)),
                ('qr_code', models.TextField(blank=True)),
                ('ack_number', models.CharField(blank=True, max_length=30)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('cancel_allowed', models.BooleanField(default=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=6)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('circuit_breaker_open', models.BooleanField(default=False)),
                ('in_dlq', models.BooleanField(default=False)),
                ('dlq_reason', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irp_submissions', to='billing.bill')),
            ],
            options={
                'db_table': 'ayy_irp_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_error_code', models.CharField(max_length=20)),
                ('final_error_message', models.TextField()),
                ('last_attempt_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='irp.invoicesubmission')),
            ],
            options={
                'db_table': 'ayy_irp_dead_letter',
            },
        ),
        migrations.CreateModel(
            name='IrpAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('request_payload', models.JSONField()),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='irp.invoicesubmission')),
            ],
            options={
                'db_table': 'ayy_irp_attempt',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicesubmission',
            index=models.Index(fields=['status', 'bill_id'], name='ayy_irp_sub_status_55cbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesubmission',
            index=models.Index(fields=['circuit_breaker_open'], name='ayy_irp_sub_circuit_1b79f4_idx'),
        ),
    ]
