# Generated by Django 5.0.14 on 2026-04-21 17:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLicence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=20, unique=True)),
                ('tier', models.CharField(default='starter', max_length=20)),
                ('features', models.JSONField(default=list)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(editable=False, max_length=512, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'ayy_licence_store',
            },
        ),
    ]
